$.extend($.validator.messages, {
    required: __('js.jquery_validate.required'),
    email: __('js.jquery_validate.email'),
    number: __('js.jquery_validate.number'),
    equalTo: __('js.jquery_validate.equalto'),
    maxlength: $.validator.format(__('js.jquery_validate.maxlength')),
    minlength: $.validator.format(__('js.jquery_validate.minlength')),
    rangelength: $.validator.format(__('js.jquery_validate.rangelength')),
    range: $.validator.format(__('js.jquery_validate.range')),
    max: $.validator.format(__('js.jquery_validate.max')),
    min: $.validator.format(__('js.jquery_validate.min')),
    //remote: "Por favor, rellena este campo.",
    //url: "Por favor, escribe una URL válida.",
    //date: "Por favor, escribe una fecha válida.",
    //dateISO: "Por favor, escribe una fecha (ISO) válida.",
    //digits: "Por favor, escribe sólo dígitos.",
    //creditcard: "Por favor, escribe un número de tarjeta válido.",
    //extension: "Por favor, escribe un valor con una extensión aceptada.",
});
